language: python
python: 2.7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- make test
cache:
  directories:
  - buildout-cache/eggs
  - buildout-cache/downloads
env:
- ROBOT_BROWSER=phantomjs
