language: python
python: 2.7
addons:
  firefox: latest
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
script:
- make test
cache:
  directories:
  - buildout-cache/eggs
  - buildout-cache/downloads
